<?php
/*	Author: 	YOUR NAME
	Date Written:	TODAY'S DATE
	Description:	Include file for demos
			automatically uses the required stylesheet
*/

echo "<!doctype html> <!-- Author:       $author -->\n";
echo "<html lang=\"en\"><!-- Date Written: $dateWritten -->\n";
echo "<head>          <!-- Description:  $description -->\n";
echo "\t<title>$title</title>\n";
echo "\t<meta charset=\"utf-8\" />\n"; 
echo "\t<link rel=\"stylesheet\" href=\"$stylesheet.css\" />\n";
echo "</head>\n";
echo "<body>\n";
echo "<div id=\"wrapper\">\n";
?>
