<?php
/*	Author: 	Brad Botteron
Date Written:	02/11/2019
Description:	htmlHeading for each page in portDisplay
*/
$path = getcwd();

echo "<!doctype html>";
echo "<html lang=\"en\">";
echo "<head>";
echo "\t<title>$title</title>\n";
echo "\t<meta charset=\"utf-8\" />\n";
echo "\t<link rel='stylesheet' href='../css/portStyle.css'";
echo "</head>\n";
echo "<body>\n";
echo "<div id=\"wrapper\">\n";

?>
